name: climlab-courseware
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - xarray
  - pip
  - metpy
  - cartopy
  - pyngl
  - sympy
  - scipy
  - ffmpeg
  - jupyterhub=3.1
  - jupyterlab
  - jupyterlab-myst
  - jupytext
  - eofs
  - intake-esm
  - gcsfs
  - proplot
  - climlab
  - numba  
  - netcdf4
  - nc-time-axis
  - conda-lock
  - xarray-datatree
# conda-lock --kind explicit -f environment.yml -p linux-64
