#######################
#######################
#
# Adapted from https://github.com/pangeo-data/pangeo-docker-images
# Under the MIT License:
# 
# Copyright (c) 2020 Pangeo Data
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#######################
#######################

FROM ubuntu:20.04

# SEE: https://github.com/phusion/baseimage-docker/issues/58
ARG DEBIAN_FRONTEND=noninteractive
ARG NB_USER="jovyan"
ARG NB_UID="2005"
ARG NB_GID="2005"

# set up environment variables
ENV CONDA_VERSION=4.10.3-2 \
    CONDA_ENV=notebook \
    NB_USER=${NB_USER} \
    NB_UID=${NB_UID} \
    NB_GID=${NB_GID} \
    SHELL=/bin/bash \
    LANG=C.UTF-8  \
    LC_ALL=C.UTF-8 \
    CONDA_DIR=/srv/conda

ENV NB_PYTHON_PREFIX=${CONDA_DIR}/envs/${CONDA_ENV} \
    HOME=/home/${NB_USER}

ENV PATH=${NB_PYTHON_PREFIX}/bin:${CONDA_DIR}/bin:${PATH}

# Create jovyan user, home folder, subfolders, set up permissions
RUN echo "Creating ${NB_USER} user and home folder structure..." \
    && groupadd --gid ${NB_GID} ${NB_USER}  \
    && useradd --create-home --gid ${NB_GID} --no-log-init --uid ${NB_UID} ${NB_USER} \
    && chown -R ${NB_USER}:${NB_GID} /srv \
    && chown -R ${NB_USER}:${NB_GID} ${HOME}

RUN echo "Installing basic apt-get packages..." \
    && apt-get update --fix-missing \
    && apt-get install -y apt-utils 2> /dev/null \
    && apt-get install -y wget zip tzdata \
    && apt-get install -y git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN echo "Copying bashrc_conda.txt and condarc.yml into the image" 
COPY --chown=${NB_USER}:${NB_GID} ./bashrc_conda.txt /tmp
COPY --chown=${NB_USER}:${NB_GID} ./condarc.yml /srv

RUN echo "Adding conda environment to /etc/profile.d and /home/jovyan/.bashrc" \
    && cat /tmp/bashrc_conda.txt >> /etc/profile.d/init_conda.sh \
    && cat /tmp/bashrc_conda.txt >> ${HOME}/.bashrc \
    && rm /tmp/bashrc_conda.txt
    
RUN echo "conda activate ${CONDA_ENV}" >> ${HOME}/.bashrc


# Switch to jovyan user
USER ${NB_USER}
WORKDIR ${HOME}

# install miniforge
RUN echo "Installing Miniforge..." \
    && URL="https://github.com/conda-forge/miniforge/releases/download/${CONDA_VERSION}/Miniforge3-${CONDA_VERSION}-Linux-x86_64.sh" \
    && wget --quiet ${URL} -O miniconda.sh \
    && /bin/bash miniconda.sh -u -b -p ${CONDA_DIR} \
    && rm miniconda.sh \
    && conda install -y -c conda-forge mamba bokeh \
    && mamba clean -afy \
    && find ${CONDA_DIR} -follow -type f -name '*.a' -delete \
    && find ${CONDA_DIR} -follow -type f -name '*.pyc' -delete

# Create "notebook" conda environment
RUN echo "Copying conda-linux-64.lock into homedir..."
COPY ./conda-linux-64.lock ${HOME}
RUN echo "Creating environment from conda-linux-64.lock..." \
    && mamba create --name ${CONDA_ENV} --file ${HOME}/conda-linux-64.lock \
    && mamba clean -yaf \
    && find ${CONDA_DIR} -follow -type f -name '*.a' -delete \
    && find ${CONDA_DIR} -follow -type f -name '*.pyc' -delete \
    && rm ${HOME}/conda-linux-64.lock

# Install pip packages
# remove cache https://github.com/pypa/pip/pull/6391 ?
RUN echo "Checking for 'postBuild'..." \
      ; if test -f "requirements.txt" ; then \
      COPY requirements.txt ${HOME} \
      && ${NB_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r ${HOME}/requirements.txt \
      && rm -rf ${HOME}/requirements.txt \
      ; fi

# Run postBuild script within ${CONDA_ENV} environment
RUN echo "Checking for 'postBuild'..." \
      ; [ -d binder ] && cd binder \
      ; [ -d .binder ] && cd .binder \
      ; if test -f "postBuild" ; then \
      export PATH=${NB_PYTHON_PREFIX}/bin:${PATH} \
      && chmod +x postBuild \
      && ./postBuild \
      && rm -rf /tmp/* \
      && rm -rf ${HOME}/.cache ${HOME}/.npm ${HOME}/.yarn \
      && rm -rf ${NB_PYTHON_PREFIX}/share/jupyter/lab/staging \
      && find ${CONDA_DIR} -follow -type f -name '*.a' -delete \
      && find ${CONDA_DIR} -follow -type f -name '*.pyc' -delete \
      && find ${CONDA_DIR} -follow -type f -name '*.js.map' -delete \
      ; fi

RUN mkdir -p ${HOME}/shared_files ${HOME}/ ${HOME}/course_notebooks ${HOME}/work ${HOME}/.jupyter
RUN chown -R ${NB_USER}:${NB_GID} ${HOME}

# Overwrite start entrypoint script if present
RUN echo "Checking for 'start'..." \
      ; [ -d binder ] && cd binder \
      ; [ -d .binder ] && cd .binder \
      ; if test -f "start" ; then \
      chmod +x start \
      && cp start /srv/start \
    ; fi


COPY jupyter_notebook_config.py /etc/jupyter/
COPY dotjupyter/ ${HOME}/.jupyter/

WORKDIR ${HOME}

CMD ["jupyterhub-singleuser"]





